[package]
name = "eid-rust-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbs = "0.4.1"
rand = "0.8.5"
pairing-plus = "0.19"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10.8"
